on:
  push:
    branches:
    - main
jobs:
  deploy:
      environment: Production
      runs-on: ubuntu-latest
      steps:
        - name: Checkout main
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: latest
            cache: npm
            cache-dependency-path: ./app/package-lock.json
        - name: Run the "npm ci" command
          run: npm ci
          working-directory: ./app
        - name: Run the "npm run build" command
          run: npm run build
          working-directory: ./app
        - run: ls app/build
        - run: tar -C app/build -cvf deploy.tar .
        - name: copy file via ssh password
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.ENV_HOST }}
            username: ${{ secrets.ENV_USERNAME }}
            password: ${{ secrets.ENV_PASSWORD }}
            port: ${{ secrets.ENV_PORT }}
            source: "deploy.tar"
            target: "/var/deployments/laconicum"
        - name: extract zip
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.ENV_HOST }}
            username: ${{ secrets.ENV_USERNAME }}
            password: ${{ secrets.ENV_PASSWORD }}
            port: ${{ secrets.ENV_PORT }}
            script: tar xf /var/deployments/laconicum/deploy.tar -C /var/www/laconicum 
